DROP TABLE IF EXISTS "actions";
CREATE TABLE "actions" ("action_id" INTEGER, "user_id" INTEGER, "world_id" INTEGER, "recource_id" INTEGER, "action" INTEGER, "amount" INTEGER, "time_start" INTEGER, "time_end" INTEGER, "duration" INTEGER);
DROP TABLE IF EXISTS "alliance";
CREATE TABLE "alliance" ("id" INTEGER, "ally_name" VARCHAR, "ally_tag" VARCHAR, "ally_owner" INTEGER, "ally_register_time" INTEGER, "ally_description" TEXT, "ally_text" TEXT, "ally_image" VARCHAR, "ally_request" TEXT, "ally_request_waiting" TEXT, "ally_request_notallow" INTEGER, "ally_owner_range" VARCHAR, "ally_ranks" TEXT, "ally_members" INTEGER);
DROP TABLE IF EXISTS "asc";
CREATE TABLE "asc" ("id" INTEGER PRIMARY KEY , "name" VARCHAR, "leader" INTEGER, "fleet_id" INTEGER, "end_time" INTEGER, "galaxy" INTEGER, "system" INTEGER, "planet" INTEGER, "planet_type" INTEGER, "users" TEXT);
DROP TABLE IF EXISTS "errors";
CREATE TABLE "errors" ("error_id" INTEGER, "error_sender" INTEGER, "error_time" VARCHAR, "error_text" VARCHAR, "error_query" TEXT);
INSERT INTO "errors" VALUES(1,234,'12435346','error here','test text');
DROP TABLE IF EXISTS "fleets";
CREATE TABLE "fleets" (
  "fleet_id" INTEGER,
  "fleet_owner" INTEGER,
  "fleet_mission" INTEGER,
  "fleet_amount" INTEGER,
  "fleet_array" TEXT,
  "fleet_start_time" INTEGER,
  "fleet_start_galaxy" INTEGER,
  "fleet_start_system" INTEGER,
  "fleet_start_planet" INTEGER,
  "fleet_start_type" INTEGER,
  "fleet_end_time" INTEGER,
  "fleet_end_stay" INTEGER,
  "fleet_end_galaxy" INTEGER,
  "fleet_end_system" INTEGER,
  "fleet_end_planet" INTEGER,
  "fleet_end_type" INTEGER,
  "fleet_target_obj" INTEGER,
  "fleet_resource_metal" INTEGER,
  "fleet_resource_crystal" INTEGER,
  "fleet_resource_deuterium" INTEGER,
  "fleet_resource_darkmatter" INTEGER,
  "fleet_target_owner" INTEGER,
  "fleet_group" VARCHAR,
  "fleet_mess" INTEGER,
  "start_time" INTEGER);
DROP TABLE IF EXISTS "galaxy";
CREATE TABLE "galaxy" (
  "galaxy" INTEGER,
  "system" INTEGER,
  "planet" INTEGER,
  "id_planet" INTEGER,
  "id_user" INTEGER,
  "metal" INTEGER,
  "crystal" INTEGER,
  "id_moon" INTEGER,
  "moon" INTEGER);
DROP TABLE IF EXISTS "messages";
CREATE TABLE "messages" (
  "message_id" INTEGER,
  "message_owner" INTEGER,
  "message_sender" INTEGER,
  "message_time" INTEGER,
  "message_type" INTEGER,
  "message_from" VARCHAR,
  "message_subject" TEXT,
  "message_text" TEXT);
DROP TABLE IF EXISTS "planets";
CREATE TABLE "planets" (
  "id_planet" INTEGER,
  "name" VARCHAR,
  "id_owner" INTEGER,
  "galaxy" INTEGER,
  "system" INTEGER,
  "planet" INTEGER,
  "last_update" INTEGER,
  "planet_type" INTEGER,
  "destroyed" INTEGER,
  "image" INTEGER,
  "diameter" INTEGER,
  "field_current" INTEGER,
  "field_max" INTEGER,
  "temp_min" INTEGER,
  "temp_max" INTEGER,
  "metal" DOUBLE,
  "metal_perhour" INTEGER,
  "metal_max" INTEGER,
  "crystal" DOUBLE,
  "crystal_perhour" INTEGER,
  "crystal_max" INTEGER,
  "deuterium" DOUBLE,
  "deuterium_perhour" INTEGER,
  "deuterium_max" INTEGER,
  "energy_used" INTEGER,
  "energy_max" INTEGER,
  "metal_mine" INTEGER,
  "crystal_mine" INTEGER,
  "deuterium_sintetizer" INTEGER,
  "solar_plant" INTEGER,
  "fusion_plant" INTEGER,
  "robot_factory" INTEGER,
  "nano_factory" INTEGER,
  "hangar" INTEGER,
  "metal_store" INTEGER,
  "crystal_store" INTEGER,
  "deuterium_store" INTEGER,
  "laboratory" INTEGER,
  "terraformer" INTEGER,
  "ally_deposit" INTEGER,
  "misil_silo" INTEGER,
  "small_ship_cargo" INTEGER,
  "big_ship_cargo" INTEGER,
  "light_hunter" INTEGER,
  "heavy_hunter" INTEGER,
  "crusher" INTEGER,
  "battle_ship" INTEGER,
  "colonizer" INTEGER,
  "recycler" INTEGER,
  "spy_sonde" INTEGER,
  "bomber_ship" INTEGER,
  "solar_satelit" INTEGER,
  "destructor" INTEGER,
  "dearth_star" INTEGER,
  "battleship" INTEGER,
  "misil_launcher" INTEGER,
  "small_laser" INTEGER,
  "big_laser" INTEGER,
  "gauss_canyon" INTEGER,
  "ionic_canyon" INTEGER,
  "buster_canyon" INTEGER,
  "small_protection_shield" INTEGER,
  "big_protection_shield" INTEGER,
  "interceptor_misil" INTEGER,
  "interplanetary_misil" INTEGER,
  "metal_mine_percent" INTEGER,
  "crystal_mine_percent" INTEGER,
  "deuterium_sintetizer_percent" INTEGER,
  "solar_plant_percent" INTEGER,
  "fusion_plant_percent" INTEGER,
  "solar_satelit_percent" INTEGER,
  "moonbase" INTEGER,
  "phalanx" INTEGER,
  "jump_gate" INTEGER,
  "last_jump_time" INTEGER);
DROP TABLE IF EXISTS "rw";
CREATE TABLE "rw" (
  "id" INTEGER,
  "owners" VARCHAR,
  "rid" VARCHAR,
  "report" TEXT,
  "time" INTEGER);
DROP TABLE IF EXISTS "users";
CREATE TABLE "users" (
  "id" INTEGER,
  "username" VARCHAR,
  "password" VARCHAR,
  "email" VARCHAR,
  "authlevel" INTEGER,
  "race" tinyint(1) NOT NULL,
  "id_planet" INTEGER,
  "galaxy" INTEGER,
  "system" INTEGER,
  "planet" INTEGER,
  "current_planet" INTEGER,
  "user_lastip" VARCHAR,
  "ip_at_reg" VARCHAR,
  "user_agent" TEXT,
  "register_time" INTEGER,
  "onlinetime" INTEGER,
  "vocation" INTEGER,
  "datedelete" INTEGER,
  "new_message" INTEGER,
  "spy_tech" INTEGER,
  "computer_tech" INTEGER,
  "weapon_tech" INTEGER,
  "shielding_tech" INTEGER,
  "armour_tech" INTEGER,
  "energy_tech" INTEGER,
  "hyperspace_tech" INTEGER,
  "combustion_tech" INTEGER,
  "impulse_motor_tech" INTEGER,
  "hyperspace_motor_tech" INTEGER,
  "laser_tech" INTEGER,
  "ionic_tech" INTEGER,
  "buster_tech" INTEGER,
  "intergalactic_tech" INTEGER,
  "astrophysics_tech" INTEGER,
  "graviton_tech" INTEGER,
  "ally_id" INTEGER,
  "ally_name" VARCHAR,
  "ally_request" INTEGER,
  "ally_request_text" TEXT,
  "ally_rank_id" INTEGER,
  "tech_points" INTEGER,
  "build_points" INTEGER,
  "defs_points" INTEGER,
  "fleet_points" INTEGER,
  "total_rank" INTEGER,
  "total_points" INTEGER,
  "off_geologist" INTEGER,
  "off_scientist" INTEGER,
  "off_engineer" INTEGER,
  "off_general" INTEGER,
  "off_admiral" INTEGER,
  "money" INTEGER,
  "ban" INTEGER,
  "ban_reason" VARCHAR,
  "uid" VARCHAR,
  "avatar" VARCHAR,
  "timezone" INTEGER,
  "starter_pack" INTEGER,
  "vip" INTEGER);
